apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-7
spec:
  selector:
    matchLabels:
      app: service-7
  replicas: 2
  template:
    metadata:
      labels:
        app: service-7
    spec:
      containers:
      - name: service-7
        image: prabakaran/service-7
        env:
        - name: API
          value: "service-8"
        ports:
        - containerPort: 80