apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-5
spec:
  selector:
    matchLabels:
      app: service-5
  replicas: 2
  template:
    metadata:
      labels:
        app: service-5
    spec:
      containers:
      - name: service-5
        image: prabakaran/service-5
        env:
        - name: API
          value: "service-6"
        ports:
        - containerPort: 80