apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
spec:
  selector:
    matchLabels:
      app: service-1
  replicas: 2
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: prabakaran/service-1
        env:
        - name: API
          value: "service-2"
        ports:
        - containerPort: 80