apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-6
spec:
  selector:
    matchLabels:
      app: service-6
  replicas: 2
  template:
    metadata:
      labels:
        app: service-6
    spec:
      containers:
      - name: service-6
        image: prabakaran/service-6
        env:
        - name: API
          value: "service-7"
        ports:
        - containerPort: 80